# All relative paths use the config file's location as their root.

# Where to put the lock file. The application will quit immediatley after
# parsing the config if it already exists. (optional)
lock_file_path: running.lock

# Where to log to. Everything except for the initialization messages will be
# logged here instead of out put. If not set or set to `null`, log messages
# will be sent to standard out.
log_file_path:  logs/run.log

# Maximum age of cached responses. If not set, responses will not be cached.
response_cache_max_age: 30 # minutes.

server:
  port: 8080

# Directory to look for templates in.
templates_dir: ./

# Any of these properties can be specified for a feed to override these
# defaults.
feed_defaults:
  # <link> value.
  link: "https://www.example.com"
  # Name of the template in `template_dir` to use for this feed.
  template: example.mrss.xml
  # A URL to an image to use if no image is present for an item. (optional)
  default_image: "https://www.example.com/default.jpg"

feeds:
    # Used in the URL.
  - id: 1234-abc
    # Feed <title>
    title: Partner MRSS Feed
    # Feed <description> (optional)
    description: Pug forage shabby chic, scenester craft beer single-origin coffee roof party brunch portland normcore.
    # See the `Provider` enum.
    provider: jw
    # The ID of the feed at the provider.
    provider_id: t5t9CjMF
